version: "3.3"

services:

#  postgresql:
#    image: 'postgres:9.6'
#    ports:
#      - '5432:5432'
#    env_file:
#      - .db-variables.env
#    restart: on-failure
#    volumes:
#      - ./postgresql:/var/lib/postgresql/data
#
#  mongodb:
#    image: 'mongo:3.6.18-xenial'
#    ports:
#      - '27017:27017'
#    env_file:
#      - .db-variables.env
#    restart: on-failure
#    volumes:
#      - ./mongodb:/data/db
#
#
#  influxdb:
#    image: 'influxdb:1.4-alpine'
#    ports:
#      - '8086:8086'
#    env_file:
#      - .db-variables.env
#    restart: on-failure
#    volumes:
#      - ./influxdb:/var/lib/influxdb


  redis:
    image: 'redis:6.0.2-alpine'
    ports:
      - '6379:6379'
    command: ["redis-server", "--bind", "redis", "--port", "6379"]



  # jeremy:
  #   image: 'coinwizard/jeremy:latest-master'
  #   command: /bin/bash /app/bin/control.sh start
  #   env_file:
  #     - .db-variables.env
  #   environment:
  #     - JEREMY_DB_HOST=postgresql
  #     - JEREMY_DB_NAME=raccoona
  #     - JEREMY_DB_USERNAME=raccoona
  #     - JEREMY_DB_PASSWORD=raccoona
  #     - JEREMY_DB_PORT=5432

  #     - JEREMY_INFLUX_HOST=influxdb
  #     - JEREMY_INFLUX_USERNAME=raccoona
  #     - JEREMY_INFLUX_DATABASE=raccoona
  #     - JEREMY_INFLUX_PASSWORD=A892sei3
  #     - JEREMY_INFLUX_PORT=8086
  #     - OPENEXCHANGERATES_APP_ID=6314d556845c4040a5ee60c45a0ab0ad
  #   ports:
  #     - '8080:8080'
  #   restart: on-failure


  # pyremy:
  #   image: 'coinwizard/pyremy:latest-master'
  #   environment:
  #     - CW_JEREMY_HOST=jeremy
  #     - CW_JEREMY_PORT=8080
  #   restart: on-failure
