version: '3'

services:
  # KeyCloak
  keycloak:
    image: quay.io/keycloak/keycloak:9.0.3
    ports:
      - "8001:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
      - KEYCLOAK_IMPORT=/tmp/loio-realm.json
    depends_on:
      - postgres
    volumes:
      - ./keycloak/loio-realm.json:/tmp/loio-realm.json

  # PostgresSQL
  postgres:
    image: postgres:11.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

